### ISSUE TITLE
Make testenv not suck (again)

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/testenv#13]
`testenv` used to be extremely solid and reliable, however overtime it's become riddled with strange issues effecting ipfs, and ipfs cluster. Chances are this is due to the way `testenv` was designed long ago and that design hasn't really changed, despite massive improvements to IPFS and IPFS Cluster.

* cluster nodes not peering
* ipfs nodes dying
* excessive
* Issues spinning up on different environments (ie, it may work for setup X, but not setup Y) which makes developing on projects using `testenv` difficult

To improve we should:

* Reduce ipfs node count to 1
* Reduce ipfs cluster node count to 1 (ipfs cluster spins up single node clusters perfectly)
* Ideally get rid of the interface mocking via `ip addr` as this isn't guaranteed to behave properly across platforms. Because we will be using single nodes, we wont have to worry about port conflicts within the containers themselves.  In theory this should drastically simplify things since we don't have to deal with adding new low level ethernet interfaces
* Configuration files for ipfs and ipfs-cluster should either be completely regenerated, or modified in such a way that the chances of out-of-date config files is less

**Comment by arku** [comment]
@postables I would like to attempt to solve this issue.
